# defaults:
#   - mj_scene: box.yaml
#   - _self_

_target_: sbto.sim.sim_mj_rollout.SimMjRollout
cfg:
  _target_: sbto.sim.sim_mj_rollout.ConfigMjRollout
  T: 500
  Nknots: 20
  Nthread: -1
  _chunk_size: 2
scaling:
  _target_: sbto.sim.action_scaling.Scaling
  name: nominal
  clip: False
