# Save figures
save_fig: true
# Save video
save_video: true
# Split state trajectory in saved data
split_state: true
# Save all samples and costs from the optimization
save_samples_costs: false
# Save all minimum costs samples per iteration 
save_best_samples_it: true
# Save top trajectories from the optimization
# if 0 < <save_top> < 1: save top <save_top>% trajectories
# if <save_top> >= 1: save top #<save_top> trajectories
save_top: 1
# Remove keys from data
remove_keys: ["x", "o"]
# Take top trajectories from the <n_last_it> last iterations only
n_last_it: 0