_target_: sbto.solvers.cem.CEM
cfg:
  _target_: sbto.solvers.cem.ConfigCEM
  N_samples: 1024
  N_it: 100
  elite_frac: 0.05
  alpha_mean: 0.95
  alpha_cov: 0.15
  std_incr: 0.
  sigma0: 0.25
  quasi_random: True
  seed: 0
  sampler: normal