_target_: sbto.solvers.cem_mom.CEMM
cfg:
  _target_: sbto.solvers.cem_mom.ConfigCEMM
  N_samples: 1024
  N_it: 100
  elite_frac: 0.04
  keep_frac: 0.03
  min_std_collapsed: 0.001
  gamma: 0.45
  std_incr: 0.0
  sigma0: 0.25
  quasi_random: False
  seed: 0
  sampler: normal