_target_: sbto.tasks.g1.pick_place_table_ref.G1PickPlaceTableRef

cfg:
  _target_: sbto.tasks.g1.pick_place_table_ref.ConfigG1PickPlaceTableRef
  # === Reference motion ===
  ref_motion_path: "./sbto/tasks/g1/motion/pick_and_place_table.pkl"
  t0: 0.5
  speedup: 2. 
  z_offset: 0.

  # === Object state goal ===
  time_lift:  0.2
  time_after_place: 0.2

  # === State costs ===
  joint_pos_weight: 0.05
  joint_vel_weight: 0.05

  # === Torso position cost ===
  torso_pos_weight: 2.
  base_pos_weight: 2.
  torso_quat_weight: 1.
  torso_quat_weight_terminal: 10.

  # === Object state costs ===
  obj_pos_weight: 30.0
  obj_quat_weight: 10.0

  # === Hand pose cost === 
  hand_position: 5.
  hand_orientation: 0.1

  # === Contact plan and cost ===
  contact_hands_weight: 1.0
  contact_obj_weight: 1.0
  contact_obj_weight_terminal: 10.0
  contact_force_obj_weight: 1.0e-3

# === Rollout simulator ===
sim:
  _target_: sbto.sim.sim_mj_rollout.SimMjRollout
  cfg:
    _target_: sbto.sim.sim_mj_rollout.ConfigMjRollout
    T: 200
    Nknots: 6
    interp_kind: linear
    Nthread: 20
    _chunk_size: 2
  scaling:
    _target_: sbto.sim.action_scaling.Scaling
    name: asymmetric
    clip: True

  # === MuJoCo Scene ===
  mj_scene:
    _target_: sbto.sim.scene_mj.MjScene
    cfg:
      _target_: sbto.sim.scene_mj.ConfigMjScene
      xml_scene_path: sbto/models/unitree_g1/scene_mjx_29dof_no_hands.xml
      xml_sensors_path: sbto/models/unitree_g1/sensors/with_obj.xml
      xml_contact_pairs_path: sbto/models/unitree_g1/contact_pairs/with_obj.xml

      # === Additional bodies ===
      add_body:
        obj:
          type: box
          pos: [0.35, 0.0, 0.715]
          size: [0.1, 0.1, 0.115]
          mass: 0.6
          euler: [0.0, 0.0, 0.0]
          rgba: [0.3, 0.3, 0.3, 1.0]
          group: 1
          freejoint: true
          priority: 0
          condim: 3
          contype: 0
          conaffinity: 1
          solref: [0.008, 1.0]
          friction: [0.6, 0.005, 0.0001]

        table:
          type: box
          pos: [0.6, 0, 0.68]
          size: [0.4, 0.8, 0.02]
          euler: [0.0, 0.0, 0.0]
          rgba: [0.8, 0.8, 0.8, 1.0]
          mass: 20
          group: 1
          contype: 1
          conaffinity: 1
          bodyname: static