_target_: sbto.tasks.g1.robot_object_ref.G1RobotObjRef

cfg:
  _target_: sbto.tasks.g1.robot_object_ref.ConfigG1RobotObjRef

  ref_motion_path: "./sbto/tasks/g1/robot-object/sub3_largebox_000_original.npz"
  t0: 0. #0.22
  speedup: 1.25
  z_offset: 0.01

  t_hand_cnt_before_lift: 0.15
  t_hand_cnt_after_place: 0.15

  # --- State costs ---
  joint_pos_weight: 0.3
  joint_vel_weight: 0.01
  base_pos_weight: 5.0
  base_quat_weight: 1.0

  # --- Torso pose/vel ---
  torso_pos_weight: 30.0
  torso_quat_weight: 2.0
  torso_quat_weight_terminal: 2.0
  torso_linvel_weight: 1.0
  torso_linvel_weight_terminal: 1.0
  torso_angvel_weight: 1.0
  torso_angvel_weight_terminal: 1.0

  # --- Foot pose cost ---
  foot_position: 15.0
  foot_orientation: 0.1

  # --- Feet Contact cost ---
  contact_feet_weight: 0.
  contact_force_feet_weight: 1.0e-6

  # --- Hand pose cost ---
  hand_position: 20.0
  hand_orientation: 0.
  hand_pos_z_mult: 2.

  # --- Obj pose cost ---
  obj_pos_weight: 20.
  obj_quat_weight: 2.
  obj_v_weight: 1.
  obj_w_weight: 2.

  # --- Obj/hands Contact cost ---
  contact_obj_weight: 0.5
  contact_hands_weight: 0.25

  collision_obj_robot: 2.

# === MuJoCo Scene ===
mj_scene_ref:
  _target_: sbto.sim.scene_mj.MjScene
  cfg:
    _target_: sbto.sim.scene_mj.ConfigMjScene
    xml_scene_path: sbto/models/unitree_g1/scene_mjx_29dof_no_hands.xml
    xml_sensors_path: sbto/models/unitree_g1/sensors/tracking_w_obj.xml
    xml_contact_pairs_path: sbto/models/unitree_g1/contact_pairs/with_obj.xml
    add_body:
    
        largebox:
          type: body_only
          pos: [0.4, 0.0, 0.1]
          euler: [0., 0., 0.]

        obj:
          type: box
          pos: [0.0, 0.0, 0.0]
          size: [0.18, 0.18, 0.18]
          euler: [3.05, 0.11, 1.11]
          mass: 0.6
          rgba: [0.3, 0.3, 0.3, 1.0]
          freejoint: true
          bodyname: largebox
          group: 1
          priority: 1
          condim: 3
          contype: 0
          conaffinity: 1
          solref: [0.008, 1.0]
          friction: [0.6, 0.005, 0.0001]

# === Rollout simulator ===
sim:
  _target_: sbto.sim.sim_mj_rollout.SimMjRollout
  cfg:
    _target_: sbto.sim.sim_mj_rollout.ConfigMjRollout
    T: 500
    Nknots: 25
    interp_kind: pchip
    Nthread: -1
    _chunk_size: 2
  scaling:
    _target_: sbto.sim.action_scaling.Scaling
    name: nominal
    clip: False

  # === MuJoCo Scene ===
  mj_scene:
    _target_: sbto.sim.scene_mj.MjScene
    cfg:
      _target_: sbto.sim.scene_mj.ConfigMjScene
      xml_scene_path: sbto/models/unitree_g1/scene_mjx_29dof_no_hands.xml
      xml_sensors_path: sbto/models/unitree_g1/sensors/tracking_w_obj.xml
      xml_contact_pairs_path: sbto/models/unitree_g1/contact_pairs/with_obj.xml
      add_body:
      
          largebox:
            type: body_only
            pos: [0.4, 0.0, 0.1]
            euler: [0., 0., 0.]

          obj:
            type: box
            pos: [0.0, 0.0, 0.0]
            size: [0.18, 0.18, 0.18]
            euler: [3.05, 0.11, 1.11]
            mass: 0.6
            rgba: [0.3, 0.3, 0.3, 1.0]
            freejoint: true
            bodyname: largebox
            group: 1
            priority: 1
            condim: 3
            contype: 0
            conaffinity: 1
            solref: [0.008, 1.0]
            friction: [0.6, 0.005, 0.0001]