_target_: sbto.tasks.g1.robot_object_ref.G1RobotObjRef

cfg:
  _target_: sbto.tasks.g1.robot_object_ref.ConfigG1RobotObjRef

  t_hand_cnt_before_lift: 0.15
  t_hand_cnt_after_place: 0.15

  # --- State costs ---
  joint_pos_weight: 0.25
  joint_vel_weight: 0.01
  base_pos_weight: 5.0
  base_quat_weight: 1.0

  # --- Torso pose/vel ---
  torso_pos_weight: 25.0
  torso_quat_weight: 2.0
  torso_quat_weight_terminal: 2.0
  torso_linvel_weight: 0.1
  torso_angvel_weight: 0.1

  # --- Foot pose cost ---
  foot_position: 15.0
  foot_orientation: 0.

  # --- Feet Contact cost ---
  contact_feet_weight: 0.
  contact_force_feet_weight: 2.0e-6

  # --- Hand pose cost ---
  # (both in world and obj ref frame)
  hand_position: 5.
  hand_orientation: 0.

  # --- Obj pose cost ---
  obj_pos_weight: 25.
  obj_pos_weight_terminal: 50.
  obj_quat_weight: 2.5
  obj_quat_weight_terminal: 5.
  obj_v_weight: 0.1
  obj_w_weight: 0.1

  # --- Obj/hands Contact cost ---
  contact_obj_weight: 2.
  contact_hands_weight: 0.5

  collision_obj_robot: 3.
  self_collision: 1.

cfg_ref:
  _target_: sbto.tasks.task_mj_ref.ConfigRefMotion
  motion_path: ./sbto/tasks/g1/motion/sub3_largebox_005_original.npz
  t0: 0.
  speedup: 1.0
  z_offset: 0.0
  override_T_sim: True

# === MuJoCo Scene ===
mj_scene_ref:
  _target_: sbto.sim.scene_mj.MjScene
  cfg:
    _target_: sbto.sim.scene_mj.ConfigMjScene
    xml_scene_path: sbto/models/unitree_g1/scene_mjx_29dof_no_hands.xml
    xml_sensors_path:
    - sbto/models/unitree_g1/sensors/feet_contact.xml
    - sbto/models/unitree_g1/sensors/feet_pos.xml
    - sbto/models/unitree_g1/sensors/hands_pos.xml
    - sbto/models/unitree_g1/sensors/obj_collision.xml
    - sbto/models/unitree_g1/sensors/obj.xml
    - sbto/models/unitree_g1/sensors/torso.xml
    xml_contact_pairs_path:
    - sbto/models/unitree_g1/contact_pairs/reduced.xml
    - sbto/models/unitree_g1/contact_pairs/robot_obj_collision.xml
    - sbto/models/unitree_g1/contact_pairs/robot_obj.xml
    add_body:
  
      chair:
        type: body_only
        pos: [0.4, 0.0, 0.1]
        euler: [0., 0., 0.]

      obj:
        type: urdf
        # pos: [0., 0., 0.0655]
        urdf_path: sbto/models/chair/chair_scaled_1.0.urdf
        pos: [-0.1, 0.05, -0.16]
        # size: [0.1, 0.1, 0.115]
        size: [0.155, 0.155, -0.18]
        euler: [3.05, 0.11, 1.11]
        mass: 0.6
        rgba: [0.3, 0.3, 0.3, 1.0]
        freejoint: true
        bodyname: chair
        group: 1
        priority: 1
        condim: 3
        contype: 0
        conaffinity: 1
        margin: 0.0
        gap: 0.0
        solref: [0.04, 1.]
        solmix: 3.
        friction: [0.6, 0.0001, 0.0001]

# === Rollout simulator ===
sim:
  _target_: sbto.sim.sim_mj_rollout.SimMjRollout
  cfg:
    _target_: sbto.sim.sim_mj_rollout.ConfigMjRollout
    T: 500
    Nknots: 25
    interp_kind: pchip
    Nthread: -1
    _chunk_size: 2
  scaling:
    _target_: sbto.sim.action_scaling.Scaling
    name: nominal
    clip: False

  # === MuJoCo Scene ===
  mj_scene:
    _target_: sbto.sim.scene_mj.MjScene
    cfg:
      _target_: sbto.sim.scene_mj.ConfigMjScene
      xml_scene_path: sbto/models/unitree_g1/scene_mjx_29dof_no_hands.xml
      xml_sensors_path:
      - sbto/models/unitree_g1/sensors/feet_contact.xml
      - sbto/models/unitree_g1/sensors/feet_pos.xml
      - sbto/models/unitree_g1/sensors/hands_pos.xml
      - sbto/models/unitree_g1/sensors/obj_collision.xml
      - sbto/models/unitree_g1/sensors/obj.xml
      - sbto/models/unitree_g1/sensors/torso.xml
      - sbto/models/unitree_g1/sensors/self_collision.xml
      xml_contact_pairs_path:
      - sbto/models/unitree_g1/contact_pairs/reduced.xml
      - sbto/models/unitree_g1/contact_pairs/robot_obj_collision.xml
      - sbto/models/unitree_g1/contact_pairs/robot_obj.xml
      add_body:
      
        largebox:
          type: body_only
          pos: [0.4, 0.0, 0.1]
          euler: [0., 0., 0.]

        chair:
          type: urdf
          # pos: [0., 0., 0.0655]
          urdf_path: sbto/models/chair/chair_scaled_1.0.urdf
          pos: [0., 0., 0.405]
          # size: [0.1, 0.1, 0.115]
          size: [0.155, 0.155, 0.17]
          euler: [3.05, 0.11, 1.11]
          mass: 0.6
          rgba: [0.3, 0.3, 0.3, 1.0]
          freejoint: true
          bodyname: largebox
          group: 1
          priority: 1
          condim: 3
          contype: 0
          conaffinity: 1
          margin: 0.0
          gap: 0.0
          solref: [0.04, 1.]
          solmix: 3.
          friction: [0.6, 0.0001, 0.0001]