defaults:
  - g1/mj_scene_ref@mj_scene_ref: box.yaml
  - g1/sim@sim: default.yaml
  - g1/sim/mj_scene@sim.mj_scene: box.yaml
  - g1/cfg_ref@cfg_ref: default.yaml
  - _self_

_target_: sbto.tasks.g1.robot_object_ref.G1RobotObjRef

cfg:
  _target_: sbto.tasks.g1.robot_object_ref.ConfigG1RobotObjRef

  t_hand_cnt_before_lift: 0.15
  t_hand_cnt_after_place: 0.15

  # --- State costs ---
  joint_pos_weight: 0.15
  joint_vel_weight: 0.01
  base_pos_weight: 5.0
  base_quat_weight: 1.0

  # --- Torso pose/vel ---
  torso_pos_weight: 25.0
  torso_quat_weight: 2.0
  torso_quat_weight_terminal: 2.0
  torso_linvel_weight: 0.1
  torso_angvel_weight: 0.1

  # --- Foot pose cost ---
  foot_position: 15.0
  foot_orientation: 0.

  # --- Feet Contact cost ---
  contact_feet_weight: 0.
  contact_force_feet_weight: 2.0e-6

  # --- Hand pose cost ---
  # (both in world and obj ref frame)
  hand_position: 5.
  hand_orientation: 0.

  # --- Obj pose cost ---
  obj_pos_weight: 40.
  obj_pos_weight_terminal: 50.
  obj_quat_weight: 2.5
  obj_quat_weight_terminal: 5.
  obj_v_weight: 0.1
  obj_w_weight: 0.1

  # --- Obj/hands Contact cost ---
  contact_obj_weight: 2.
  contact_hands_weight: 0.5

  collision_obj_robot: 3.
  self_collision: 1.